<h1>List</h1>
<?php 
    $user_m = new UserManager;
    $tab_user = $user_m->findAll(); ?>

    <div>
        <?php foreach ($tab_user as $user){ ?>
        <tr>
            <td><?= $user['id'] ?></td>
            <td><?= $user['first_name'] ?></td>
            <td><?= $user['last_name'] ?></td>
            <td><?= $user['email'] ?></td>
            <td><a href="?route=show_user&id=<?= $user['id'] ?>">afficher</a></td>
            <td><a href="?route=update_user&id=<?= $user['id'] ?>">modifier</a></td>
            <td><a href="?route=delete_user&id=<?= $user['id'] ?>">delete</a></td>
         </tr>
    <?php } ?>
    </div>
