<main id="login">
    <fieldset class="card">
        <legend>Login</legend>
        <form method="post" action=".">
            <div>
                <label for="email">Email:</label>
                <input type="text" id="email" name="email" required>
            </div>
            <div id="last-input">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit">Se Connecter</button>
        </form>
        <div>
            <a href="./index.php?route=register">S'inscrire</a>
        </div>
    </fieldset>
</main>