<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="assets/style/css/style.css">
    <link rel="stylesheet" href="assets/style/css/identification.css">
    <link rel="stylesheet" href="assets/style/css/home.css">
    <link rel="stylesheet" href="assets/style/css/ajouter-depenser.css">
    <link rel="stylesheet" href="assets/style/css/rembourser.css">
    <script src="assets/js/script.js"></script>
    <title>FairCount</title>
</head>
<body>
    <?php require "templates/partials/$template.phtml"; ?>
</body>
</html>